#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 352)

def self.parse(sql)
  new.scan_str(sql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    48,    73,    73,    59,   -16,   251,   286,  -139,    82,   112,
   287,   -16,   -16,   -16,    76,   257,    73,    73,   280,   281,
     7,   258,   151,     8,   113,   288,   115,   116,    48,   117,
   118,   236,   237,   174,   289,    66,    78,    21,  -139,  -139,
  -139,  -139,    83,    59,   246,    51,    52,    74,    74,    35,
    49,    39,    41,    42,    43,    44,    45,   181,    53,    94,
    56,    48,    74,    74,   178,    21,   174,    51,    52,  -133,
    78,   119,    59,    51,    52,    66,   214,    35,    49,    39,
    41,    42,    43,    44,    45,     9,    53,    48,    56,    53,
   181,    56,   251,    78,    53,    11,    56,   178,    21,    12,
  -133,  -133,  -133,  -133,    66,    57,    51,    52,    98,    97,
    35,    49,    39,    41,    42,    43,    44,    45,    58,    53,
    48,    56,   -14,    75,    21,    31,    79,    80,    81,   -14,
   -14,   -14,    51,    52,    17,   112,    35,    49,    39,    41,
    42,    43,    44,    45,    48,    53,   -94,    56,    87,   251,
   113,   -15,   115,   116,    88,   117,   118,    21,   -15,   -15,
   -15,   248,    89,   249,   250,    51,    52,   155,   156,    35,
    49,    39,    41,    42,    43,    44,    45,    48,    53,    90,
    56,    21,   251,    91,    92,    93,  -159,    94,    95,    51,
    52,    96,    99,    35,    49,    39,    41,    42,    43,    44,
    45,    48,    53,     8,    56,    74,   251,   129,    78,   138,
    78,   147,   152,   153,    21,   157,   111,   161,    66,   163,
   164,   165,    51,    52,   166,   167,    35,    49,    39,    41,
    42,    43,    44,    45,    48,    53,    78,    56,    21,   251,
    74,    74,    74,   173,   194,   195,    51,    52,   196,   197,
    35,    49,    39,    41,    42,    43,    44,    45,    48,    53,
   198,    56,   199,   251,   200,   201,   203,   204,    66,   210,
   211,    21,   214,    59,   228,   231,   232,   238,   138,    51,
    52,   253,   268,    35,    49,    39,    41,    42,    43,    44,
    45,    48,    53,   269,    56,    21,   251,   214,   270,   228,
   253,   274,   276,    51,    52,   214,    78,    35,    49,    39,
    41,    42,    43,    44,    45,   283,    53,   285,    56,    48,
   nil,   nil,   nil,   nil,   174,   nil,   nil,   nil,    21,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,   181,    53,
  -152,    56,    48,   nil,   nil,   178,    21,    31,   nil,   nil,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,   nil,    53,   nil,    56,
    48,  -152,  -152,  -152,  -152,   174,   nil,   nil,   nil,    21,
   nil,   nil,   nil,  -159,   nil,   nil,   nil,    51,    52,   nil,
   nil,    35,    49,    39,    41,    42,    43,    44,    45,   181,
    53,   nil,    56,    48,   nil,   nil,   178,    21,    31,   nil,
   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,
    49,    39,    41,    42,    43,    44,    45,    48,    53,   nil,
    56,   nil,    31,   215,   216,   nil,   217,   218,   219,   nil,
    21,   nil,   nil,   220,   221,   222,   223,   224,   225,   nil,
   nil,   nil,    35,    49,    39,    41,    42,    43,    44,    45,
    48,    53,   nil,    56,    21,   251,   nil,   nil,   nil,   nil,
   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,
    42,    43,    44,    45,    48,    53,   nil,    56,   nil,    31,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,    17,   nil,
   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,
    49,    39,    41,    42,    43,    44,    45,    48,    53,   nil,
    56,    21,    31,   nil,   nil,   nil,   nil,     8,   nil,    51,
    52,   nil,   nil,    35,    49,    39,    41,    42,    43,    44,
    45,    48,    53,   nil,    56,   nil,    31,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,
    42,    43,    44,    45,    48,    53,   nil,    56,    21,    31,
   nil,   nil,   nil,   nil,     8,   nil,    51,    52,   nil,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,   105,    53,
   nil,    56,   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    21,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,
    52,   nil,   nil,    35,    49,    39,    41,    42,    43,    44,
    45,    48,    53,   nil,    56,    21,    31,   nil,   nil,   nil,
   nil,   nil,   nil,    51,    52,    17,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    48,    53,   nil,    56,   nil,
    31,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,    48,    53,
   nil,    56,    21,    31,   nil,   nil,   nil,   nil,   nil,   nil,
    51,    52,   nil,   nil,    35,    49,    39,    41,    42,    43,
    44,    45,    48,    53,   nil,    56,   nil,    31,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    48,    53,   nil,    56,    21,
    31,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,
   nil,    35,    49,    39,    41,    42,    43,    44,    45,    48,
    53,   nil,    56,   nil,    31,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    21,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    51,    52,   nil,   nil,    35,    49,    39,    41,    42,    43,
    44,    45,    48,    53,   nil,    56,    21,    31,   nil,   nil,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    48,    53,   nil,    56,
   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,
   nil,    35,    49,    39,    41,    42,    43,    44,    45,   nil,
    53,   105,    56,    21,   nil,   nil,    31,   nil,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    48,    53,   nil,    56,   nil,    31,   nil,
   nil,   nil,   nil,   nil,    13,    14,    15,    17,    21,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,   nil,    53,
    21,    56,   nil,   nil,   nil,   nil,    48,   nil,    51,    52,
   nil,    31,    35,    49,    39,    41,    42,    43,    44,    45,
   140,    53,   nil,    56,   nil,   nil,    48,   nil,   nil,   112,
   nil,    31,   110,   nil,   nil,   nil,   111,   nil,   nil,   nil,
   nil,   nil,   nil,    21,   113,   nil,   115,   116,    48,   117,
   118,    51,    52,    31,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    21,    53,   nil,    56,   nil,    48,   nil,
   nil,    51,    52,    31,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,   nil,    53,    21,    56,   nil,   nil,   nil,
    48,   nil,   nil,    51,    52,    31,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    21,    53,   nil,    56,   nil,
   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,   nil,    53,    21,    56,   nil,
   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,
    49,    39,    41,    42,    43,    44,    45,    48,    53,   nil,
    56,   nil,   174,   nil,   nil,   nil,   nil,     8,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    48,   nil,   nil,
   nil,   nil,    31,   nil,   nil,   nil,   181,   nil,   nil,   nil,
   nil,   nil,   nil,   178,    21,   nil,   nil,   nil,   nil,    48,
   nil,   nil,    51,    52,    31,   nil,    35,    49,    39,    41,
    42,    43,    44,    45,    21,    53,   nil,    56,   nil,   nil,
   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,
    42,    43,    44,    45,    48,    53,    21,    56,   nil,   174,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    48,    53,   nil,    56,
   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   178,    21,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,
    52,   nil,   nil,    35,    49,    39,    41,    42,    43,    44,
    45,    48,    53,    21,    56,   nil,   174,   nil,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    48,    53,   nil,    56,   nil,    31,   nil,
   181,   nil,   nil,   nil,   nil,   nil,   nil,   178,    21,   nil,
   nil,   nil,   nil,    48,   nil,   nil,    51,    52,   251,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,   nil,    53,
    21,    56,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,
   nil,   nil,    35,    49,    39,    41,    42,    43,    44,    45,
    21,    53,   nil,    56,   nil,   nil,   nil,   nil,    51,    52,
   nil,   nil,    35,    49,    39,    41,    42,    43,    44,    45,
   nil,    53,   nil,    56 ]

racc_action_check = [
   274,    68,    16,    12,   105,   274,   277,    23,    25,   208,
   278,   105,   105,   105,    20,   219,    69,    67,   269,   269,
     0,   219,    96,     0,   208,   280,   208,   208,   214,   208,
   208,   208,   208,   214,   281,    12,    20,   274,    23,    23,
    23,    23,    25,    73,   212,   274,   274,    68,    16,   274,
   274,   274,   274,   274,   274,   274,   274,   214,   274,   105,
   274,   129,    69,    67,   214,   214,   129,    96,    96,   244,
   287,    61,   164,   214,   214,    73,   212,   214,   214,   214,
   214,   214,   214,   214,   214,     1,   214,   216,   214,   250,
   129,   250,   216,    61,   218,     5,   218,   129,   129,     7,
   244,   244,   244,   244,   164,     9,   129,   129,    53,    53,
   129,   129,   129,   129,   129,   129,   129,   129,    11,   129,
    15,   129,   103,    19,   216,    15,    24,    24,    24,   103,
   103,   103,   216,   216,    15,   130,   216,   216,   216,   216,
   216,   216,   216,   216,   220,   216,    21,   216,    36,   220,
   130,   104,   130,   130,    39,   130,   130,    15,   104,   104,
   104,   215,    41,   215,   215,    15,    15,   102,   102,    15,
    15,    15,    15,    15,    15,    15,    15,   221,    15,    42,
    15,   220,   221,    43,    44,    45,    46,    48,    49,   220,
   220,    50,    56,   220,   220,   220,   220,   220,   220,   220,
   220,   222,   220,    59,   220,    70,   222,    72,    76,    86,
    87,    94,    97,   100,   221,   107,   109,   111,   112,   113,
   114,   116,   221,   221,   117,   118,   221,   221,   221,   221,
   221,   221,   221,   221,   223,   221,   119,   221,   222,   223,
   121,   123,   125,   128,   140,   141,   222,   222,   142,   143,
   222,   222,   222,   222,   222,   222,   222,   222,   224,   222,
   144,   222,   145,   224,   146,   150,   159,   160,   163,   172,
   173,   223,   175,   178,   179,   205,   206,   209,   213,   223,
   223,   217,   237,   223,   223,   223,   223,   223,   223,   223,
   223,   225,   223,   238,   223,   224,   225,   240,   241,   247,
   249,   252,   257,   224,   224,   267,   268,   224,   224,   224,
   224,   224,   224,   224,   224,   271,   224,   275,   224,   228,
   nil,   nil,   nil,   nil,   228,   nil,   nil,   nil,   225,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   225,   225,   nil,   nil,
   225,   225,   225,   225,   225,   225,   225,   225,   228,   225,
   243,   225,   232,   nil,   nil,   228,   228,   232,   nil,   nil,
   nil,   nil,   nil,   nil,   228,   228,   nil,   nil,   228,   228,
   228,   228,   228,   228,   228,   228,   nil,   228,   nil,   228,
   236,   243,   243,   243,   243,   236,   nil,   nil,   nil,   232,
   nil,   nil,   nil,   243,   nil,   nil,   nil,   232,   232,   nil,
   nil,   232,   232,   232,   232,   232,   232,   232,   232,   236,
   232,   nil,   232,    26,   nil,   nil,   236,   236,    26,   nil,
   nil,   nil,   nil,   nil,   nil,   236,   236,   nil,   nil,   236,
   236,   236,   236,   236,   236,   236,   236,   110,   236,   nil,
   236,   nil,   110,   177,   177,   nil,   177,   177,   177,   nil,
    26,   nil,   nil,   177,   177,   177,   177,   177,   177,   nil,
   nil,   nil,    26,    26,    26,    26,    26,    26,    26,    26,
   248,    26,   nil,    26,   110,   248,   nil,   nil,   nil,   nil,
   nil,   nil,   110,   110,   nil,   nil,   110,   110,   110,   110,
   110,   110,   110,   110,    14,   110,   nil,   110,   nil,    14,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   248,    14,   nil,
   nil,   nil,   nil,   nil,   nil,   248,   248,   nil,   nil,   248,
   248,   248,   248,   248,   248,   248,   248,   251,   248,   nil,
   248,    14,   251,   nil,   nil,   nil,   nil,   251,   nil,    14,
    14,   nil,   nil,    14,    14,    14,    14,    14,    14,    14,
    14,    31,    14,   nil,    14,   nil,    31,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   251,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   251,   251,   nil,   nil,   251,   251,   251,   251,
   251,   251,   251,   251,   253,   251,   nil,   251,    31,   253,
   nil,   nil,   nil,   nil,   253,   nil,    31,    31,   nil,   nil,
    31,    31,    31,    31,    31,    31,    31,    31,    58,    31,
   nil,    31,   nil,    58,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   253,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   253,
   253,   nil,   nil,   253,   253,   253,   253,   253,   253,   253,
   253,    13,   253,   nil,   253,    58,    13,   nil,   nil,   nil,
   nil,   nil,   nil,    58,    58,    13,   nil,    58,    58,    58,
    58,    58,    58,    58,    58,   270,    58,   nil,    58,   nil,
   270,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    13,    13,   nil,   nil,
    13,    13,    13,    13,    13,    13,    13,    13,    75,    13,
   nil,    13,   270,    75,   nil,   nil,   nil,   nil,   nil,   nil,
   270,   270,   nil,   nil,   270,   270,   270,   270,   270,   270,
   270,   270,    79,   270,   nil,   270,   nil,    79,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    75,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    75,    75,   nil,   nil,    75,    75,    75,
    75,    75,    75,    75,    75,    80,    75,   nil,    75,    79,
    80,   nil,   nil,   nil,   nil,   nil,   nil,    79,    79,   nil,
   nil,    79,    79,    79,    79,    79,    79,    79,    79,    81,
    79,   nil,    79,   nil,    81,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    80,    80,   nil,   nil,    80,    80,    80,    80,    80,    80,
    80,    80,    82,    80,   nil,    80,    81,    82,   nil,   nil,
   nil,   nil,   nil,   nil,    81,    81,   nil,   nil,    81,    81,
    81,    81,    81,    81,    81,    81,    83,    81,   nil,    81,
   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82,    82,   nil,
   nil,    82,    82,    82,    82,    82,    82,    82,    82,   nil,
    82,   153,    82,    83,   nil,   nil,   153,   nil,   nil,   nil,
   nil,    83,    83,   nil,   nil,    83,    83,    83,    83,    83,
    83,    83,    83,     8,    83,   nil,    83,   nil,     8,   nil,
   nil,   nil,   nil,   nil,     8,     8,     8,     8,   153,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   153,   153,   nil,   nil,
   153,   153,   153,   153,   153,   153,   153,   153,   nil,   153,
     8,   153,   nil,   nil,   nil,   nil,    88,   nil,     8,     8,
   nil,    88,     8,     8,     8,     8,     8,     8,     8,     8,
    88,     8,   nil,     8,   nil,   nil,   161,   nil,   nil,    60,
   nil,   161,    60,   nil,   nil,   nil,    60,   nil,   nil,   nil,
   nil,   nil,   nil,    88,    60,   nil,    60,    60,    89,    60,
    60,    88,    88,    89,   nil,    88,    88,    88,    88,    88,
    88,    88,    88,   161,    88,   nil,    88,   nil,    90,   nil,
   nil,   161,   161,    90,   nil,   161,   161,   161,   161,   161,
   161,   161,   161,   nil,   161,    89,   161,   nil,   nil,   nil,
    91,   nil,   nil,    89,    89,    91,   nil,    89,    89,    89,
    89,    89,    89,    89,    89,    90,    89,   nil,    89,   nil,
   nil,   nil,   nil,    90,    90,   nil,   nil,    90,    90,    90,
    90,    90,    90,    90,    90,   nil,    90,    91,    90,   nil,
   nil,   nil,   nil,   nil,   nil,    91,    91,   nil,   nil,    91,
    91,    91,    91,    91,    91,    91,    91,   174,    91,   nil,
    91,   nil,   174,   nil,   nil,   nil,   nil,   174,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    92,   nil,   nil,
   nil,   nil,    92,   nil,   nil,   nil,   174,   nil,   nil,   nil,
   nil,   nil,   nil,   174,   174,   nil,   nil,   nil,   nil,    93,
   nil,   nil,   174,   174,    93,   nil,   174,   174,   174,   174,
   174,   174,   174,   174,    92,   174,   nil,   174,   nil,   nil,
   nil,   nil,    92,    92,   nil,   nil,    92,    92,    92,    92,
    92,    92,    92,    92,   181,    92,    93,    92,   nil,   181,
   nil,   nil,   nil,   nil,    93,    93,   nil,   nil,    93,    93,
    93,    93,    93,    93,    93,    93,   204,    93,   nil,    93,
   nil,   204,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   181,   181,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   181,
   181,   nil,   nil,   181,   181,   181,   181,   181,   181,   181,
   181,   210,   181,   204,   181,   nil,   210,   nil,   nil,   nil,
   nil,   204,   204,   nil,   nil,   204,   204,   204,   204,   204,
   204,   204,   204,   211,   204,   nil,   204,   nil,   211,   nil,
   210,   nil,   nil,   nil,   nil,   nil,   nil,   210,   210,   nil,
   nil,   nil,   nil,   283,   nil,   nil,   210,   210,   283,   nil,
   210,   210,   210,   210,   210,   210,   210,   210,   nil,   210,
   211,   210,   nil,   nil,   nil,   nil,   nil,   nil,   211,   211,
   nil,   nil,   211,   211,   211,   211,   211,   211,   211,   211,
   283,   211,   nil,   211,   nil,   nil,   nil,   nil,   283,   283,
   nil,   nil,   283,   283,   283,   283,   283,   283,   283,   283,
   nil,   283,   nil,   283 ]

racc_action_pointer = [
     8,    85,   nil,   nil,   nil,    93,   nil,    86,   888,   105,
   nil,   115,    -7,   636,   489,   115,   -19,   nil,   nil,   116,
    -6,    91,   nil,   -12,    76,   -11,   408,   nil,   nil,   nil,
   nil,   546,   nil,   nil,   nil,   nil,    93,   nil,   nil,   144,
   nil,   152,   169,   173,   174,   175,   124,   nil,   132,   183,
   129,   nil,   nil,    45,   nil,   nil,   126,   nil,   603,   188,
   952,    51,   nil,   nil,   nil,   nil,   nil,    -4,   -20,    -5,
   138,   nil,   176,    33,   nil,   693,   166,   nil,   nil,   717,
   750,   774,   807,   831,   nil,   nil,   198,   168,   931,   973,
   993,  1015,  1092,  1114,   206,   nil,    17,   149,   nil,   nil,
   206,   nil,   159,   122,   151,     4,   nil,   204,   nil,   202,
   432,   207,   176,   196,   197,   nil,   195,   198,   199,   194,
   nil,   173,   nil,   174,   nil,   175,   nil,   nil,   211,    56,
   128,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   233,   234,   237,   238,   249,   251,   253,   nil,   nil,   nil,
   260,   nil,   nil,   866,   nil,   nil,   nil,   nil,   nil,   255,
   260,   951,   nil,   226,    62,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   236,   267,  1072,   229,   nil,   409,   263,   238,
   nil,  1149,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,  1171,   264,   269,   nil,     2,   273,
  1206,  1228,    33,   267,    23,   126,    82,   271,    31,   -19,
   139,   172,   196,   229,   253,   286,   nil,   nil,   314,   nil,
   nil,   nil,   347,   nil,   nil,   nil,   375,   272,   288,   nil,
   254,   291,   nil,   331,    50,   nil,   nil,   263,   465,   290,
    26,   522,   265,   579,   nil,   nil,   nil,   262,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   262,   264,    12,
   660,   279,   nil,   nil,    -5,   306,   nil,    -5,     3,   nil,
    20,    29,   nil,  1248,   nil,   nil,   nil,    28,   nil,   nil,
   nil,   nil ]

racc_action_default = [
  -173,  -173,    -1,    -2,    -3,    -5,   -22,  -173,  -173,  -173,
    -4,  -173,  -173,  -173,  -173,  -173,  -172,   -37,   -38,   -40,
   -43,  -165,  -121,  -122,  -126,  -129,  -173,  -131,  -132,  -133,
  -134,  -173,  -136,  -137,  -138,  -140,  -173,  -142,  -143,  -173,
  -145,  -173,  -173,  -173,  -173,  -173,  -152,  -153,  -157,  -173,
  -173,  -163,  -164,  -173,  -168,  -169,  -173,   292,  -173,  -173,
  -173,   -48,   -49,   -50,   -52,   -53,   -94,  -172,  -172,  -172,
  -172,   -36,   -69,  -173,  -171,  -173,  -173,   -42,  -165,  -173,
  -173,  -173,  -173,  -173,  -130,  -139,  -173,  -173,  -173,  -173,
  -173,  -173,  -173,  -173,  -155,  -156,  -173,  -173,  -167,  -170,
    -6,   -12,   -18,  -133,  -134,  -157,   -17,  -173,   -23,  -173,
  -173,  -173,  -173,  -173,  -173,   -57,   -59,   -61,   -62,  -173,
   -47,  -172,   -30,  -172,   -32,  -172,   -34,   -35,   -71,  -173,
   -45,   -39,   -41,  -123,  -124,  -125,  -127,  -128,  -135,  -141,
  -173,  -173,  -173,  -173,  -173,  -173,  -173,  -154,  -158,  -160,
  -173,  -162,  -166,  -173,   -13,   -19,   -20,   -21,   -24,  -173,
   -27,  -173,   -54,  -173,  -173,   -58,   -60,   -63,   -46,   -29,
   -31,   -33,   -78,  -173,  -173,   -70,   -80,  -173,  -173,   -97,
   -99,  -173,  -102,  -103,  -104,  -106,  -107,  -108,  -109,  -110,
  -111,  -118,  -119,  -120,  -144,  -146,  -147,  -148,  -149,  -150,
  -151,  -161,   -11,   -25,  -173,  -173,   -88,   -55,  -173,    -7,
  -173,  -173,  -173,  -120,  -173,  -173,  -173,  -173,  -173,  -173,
  -173,  -173,  -173,  -173,  -173,  -173,   -51,   -93,  -173,  -101,
   -26,   -28,  -173,   -56,   -64,   -65,  -173,  -173,  -173,   -44,
   -79,   -72,   -74,   -75,   -76,   -77,  -105,   -98,  -173,  -173,
  -173,  -173,  -173,  -173,   -84,   -85,   -90,  -173,   -92,  -112,
  -113,  -114,  -115,  -116,  -117,  -100,   -87,   -66,  -173,    -8,
  -173,  -173,   -83,   -89,  -173,  -173,   -91,  -173,   -68,   -96,
  -173,  -173,   -73,  -173,   -82,   -86,   -67,  -173,    -9,   -10,
   -81,   -95 ]

racc_goto_table = [
    77,    20,   103,   101,    62,   106,    20,    20,    20,    71,
   175,   104,   254,    61,    60,   159,    85,   243,   205,   242,
   136,   137,   265,   229,    86,   150,   133,   134,   135,    16,
   108,    84,   148,     1,    67,    68,    69,   149,     2,     3,
     4,   120,    70,     5,   272,    10,   100,   239,    85,   154,
   109,   131,   128,   172,   209,   212,   132,   227,   233,   234,
   122,   124,   126,   127,   235,    62,   277,   139,    20,    85,
    85,    85,    85,    85,    61,   130,   243,   278,   282,   158,
   241,   141,   142,   143,   144,   145,   146,   247,   nil,   266,
   nil,   240,   nil,   121,   123,   125,   nil,   103,   202,   168,
   106,   nil,   nil,   160,   nil,   nil,   104,   nil,   nil,   230,
   275,   nil,   nil,   162,   169,   252,   170,   267,   171,   259,
   260,   261,   262,   263,   264,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    85,   nil,   nil,   nil,   271,   nil,   nil,
   nil,   nil,   nil,   nil,   206,   244,    62,   nil,   245,   nil,
   nil,   nil,   nil,   nil,   207,    61,   208,   213,   nil,   nil,
   226,   nil,   nil,   284,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   290,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   160,   nil,   nil,
   nil,    85,   nil,   nil,   nil,   nil,   nil,   nil,   256,   226,
   nil,   nil,   nil,   nil,   244,   nil,   nil,   245,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   206,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   273,   226,   nil,   nil,    86,   nil,   206,   nil,   279,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    85,   nil,   nil,   nil,   nil,   nil,   nil,   291 ]

racc_goto_check = [
    28,    21,    12,     9,    15,    14,    21,    21,    21,    25,
    42,    13,    52,    33,    17,    20,    54,    47,    22,    46,
    64,    64,    58,    59,    21,    66,    14,    14,    14,    23,
    18,    67,    76,     1,    23,    23,    23,    77,     2,     3,
     4,    28,    24,     5,    52,     6,     7,     8,    54,    11,
    19,    26,    30,    31,    32,    42,    28,    35,    39,    40,
    25,    25,    25,    25,    41,    15,    43,    28,    21,    54,
    54,    54,    54,    54,    33,    17,    47,    44,    46,    18,
    45,    21,    21,    21,    21,    21,    21,    57,   nil,    22,
   nil,    42,   nil,    24,    24,    24,   nil,    12,     9,    28,
    14,   nil,   nil,    21,   nil,   nil,    13,   nil,   nil,    20,
    22,   nil,   nil,    33,    25,    50,    25,    42,    25,    50,
    50,    50,    50,    50,    50,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    54,   nil,   nil,   nil,    50,   nil,   nil,
   nil,   nil,   nil,   nil,    21,    12,    15,   nil,    14,   nil,
   nil,   nil,   nil,   nil,    33,    33,    17,    21,   nil,   nil,
    15,   nil,   nil,    50,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    50,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,    54,   nil,   nil,   nil,   nil,   nil,   nil,    54,    15,
   nil,   nil,   nil,   nil,    12,   nil,   nil,    14,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    54,    15,   nil,   nil,    21,   nil,    21,   nil,    28,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    54,   nil,   nil,   nil,   nil,   nil,   nil,    28 ]

racc_goto_pointer = [
   nil,    33,    38,    39,    40,    43,    40,   -12,  -162,   -55,
   nil,   -53,   -56,   -47,   -53,    -8,   nil,     2,   -30,   -10,
   -95,    -7,  -143,    21,    26,    -7,   -24,   nil,   -20,   nil,
   -20,   -75,  -118,     1,   nil,  -121,   nil,   nil,   nil,  -150,
  -149,  -144,  -119,  -202,  -191,  -131,  -192,  -194,   nil,   nil,
  -101,   nil,  -205,   nil,   -10,   nil,   nil,  -127,  -206,  -158,
   nil,   nil,   nil,   nil,   -62,   nil,   -71,     5,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -64,   -59,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   107,   nil,   nil,   nil,   nil,
   102,   nil,    29,    30,    22,   176,     6,   nil,   nil,   nil,
   nil,   193,   nil,   nil,   nil,   nil,    18,    19,    37,    72,
   nil,   nil,   nil,    38,    63,   255,    64,    65,   114,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    46,   192,   186,
   177,   187,   nil,   188,    23,   189,   190,   179,   180,   182,
   183,   184,   185,   191,    24,    25,    26,    27,    28,    32,
    33,    34,    36,    40,    47,    50,   nil,   nil,    54,    55 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 69, :_reduce_none,
  1, 70, :_reduce_none,
  1, 70, :_reduce_none,
  2, 71, :_reduce_4,
  0, 74, :_reduce_none,
  3, 74, :_reduce_6,
  0, 76, :_reduce_none,
  2, 76, :_reduce_8,
  4, 76, :_reduce_9,
  4, 76, :_reduce_10,
  3, 75, :_reduce_11,
  1, 75, :_reduce_none,
  2, 77, :_reduce_13,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_16,
  1, 78, :_reduce_none,
  0, 79, :_reduce_18,
  1, 79, :_reduce_19,
  1, 79, :_reduce_20,
  3, 83, :_reduce_21,
  1, 73, :_reduce_none,
  4, 72, :_reduce_23,
  5, 72, :_reduce_24,
  3, 87, :_reduce_25,
  3, 88, :_reduce_26,
  1, 88, :_reduce_none,
  4, 86, :_reduce_28,
  5, 84, :_reduce_29,
  4, 84, :_reduce_30,
  5, 84, :_reduce_31,
  4, 84, :_reduce_32,
  5, 84, :_reduce_33,
  4, 84, :_reduce_34,
  4, 84, :_reduce_35,
  3, 84, :_reduce_36,
  1, 91, :_reduce_37,
  1, 91, :_reduce_38,
  3, 94, :_reduce_39,
  1, 94, :_reduce_none,
  3, 95, :_reduce_41,
  2, 95, :_reduce_42,
  1, 95, :_reduce_none,
  5, 92, :_reduce_44,
  2, 97, :_reduce_45,
  3, 85, :_reduce_46,
  2, 85, :_reduce_47,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 85, :_reduce_none,
  1, 103, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  3, 104, :_reduce_54,
  4, 104, :_reduce_55,
  5, 105, :_reduce_56,
  1, 106, :_reduce_57,
  2, 106, :_reduce_58,
  1, 106, :_reduce_59,
  2, 106, :_reduce_60,
  1, 106, :_reduce_61,
  1, 106, :_reduce_62,
  2, 106, :_reduce_63,
  1, 107, :_reduce_none,
  1, 107, :_reduce_none,
  2, 108, :_reduce_66,
  4, 109, :_reduce_67,
  1, 111, :_reduce_none,
  0, 98, :_reduce_none,
  2, 98, :_reduce_70,
  0, 99, :_reduce_none,
  3, 99, :_reduce_72,
  3, 113, :_reduce_73,
  1, 113, :_reduce_none,
  1, 114, :_reduce_none,
  1, 114, :_reduce_none,
  1, 114, :_reduce_none,
  0, 100, :_reduce_none,
  2, 100, :_reduce_79,
  1, 116, :_reduce_none,
  6, 117, :_reduce_81,
  5, 117, :_reduce_82,
  4, 119, :_reduce_83,
  3, 119, :_reduce_84,
  1, 120, :_reduce_none,
  3, 120, :_reduce_86,
  3, 90, :_reduce_87,
  1, 90, :_reduce_none,
  4, 121, :_reduce_89,
  3, 121, :_reduce_90,
  4, 123, :_reduce_91,
  3, 123, :_reduce_92,
  2, 124, :_reduce_93,
  1, 101, :_reduce_94,
  3, 112, :_reduce_95,
  1, 112, :_reduce_none,
  1, 110, :_reduce_none,
  3, 110, :_reduce_98,
  1, 125, :_reduce_none,
  3, 125, :_reduce_100,
  2, 126, :_reduce_101,
  1, 126, :_reduce_none,
  1, 127, :_reduce_none,
  1, 128, :_reduce_none,
  3, 128, :_reduce_105,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  3, 130, :_reduce_112,
  3, 130, :_reduce_113,
  3, 130, :_reduce_114,
  3, 130, :_reduce_115,
  3, 130, :_reduce_116,
  3, 130, :_reduce_117,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  1, 131, :_reduce_none,
  1, 89, :_reduce_none,
  1, 89, :_reduce_none,
  3, 82, :_reduce_123,
  3, 82, :_reduce_124,
  3, 82, :_reduce_125,
  1, 82, :_reduce_none,
  3, 132, :_reduce_127,
  3, 132, :_reduce_128,
  1, 132, :_reduce_none,
  2, 133, :_reduce_130,
  1, 133, :_reduce_none,
  1, 135, :_reduce_none,
  1, 135, :_reduce_none,
  1, 135, :_reduce_none,
  3, 135, :_reduce_135,
  1, 136, :_reduce_none,
  1, 136, :_reduce_none,
  1, 137, :_reduce_none,
  1, 137, :_reduce_none,
  1, 138, :_reduce_140,
  3, 80, :_reduce_141,
  1, 80, :_reduce_none,
  1, 140, :_reduce_none,
  4, 81, :_reduce_144,
  1, 81, :_reduce_none,
  4, 141, :_reduce_146,
  4, 141, :_reduce_147,
  4, 141, :_reduce_148,
  4, 141, :_reduce_149,
  4, 141, :_reduce_150,
  4, 141, :_reduce_151,
  1, 139, :_reduce_none,
  1, 139, :_reduce_none,
  3, 115, :_reduce_154,
  2, 115, :_reduce_155,
  2, 115, :_reduce_156,
  1, 115, :_reduce_157,
  3, 142, :_reduce_158,
  1, 143, :_reduce_none,
  1, 144, :_reduce_none,
  2, 145, :_reduce_161,
  1, 145, :_reduce_162,
  1, 134, :_reduce_163,
  1, 134, :_reduce_164,
  1, 96, :_reduce_165,
  3, 122, :_reduce_166,
  2, 122, :_reduce_167,
  1, 122, :_reduce_none,
  1, 146, :_reduce_none,
  2, 147, :_reduce_170,
  1, 93, :_reduce_none,
  0, 93, :_reduce_none ]

racc_reduce_n = 173

racc_shift_n = 292

racc_token_table = {
  false => 0,
  :error => 1,
  :ORDER => 2,
  :BY => 3,
  :LIMIT => 4,
  :unsigned_integer => 5,
  :OFFSET => 6,
  :comma => 7,
  :ASC => 8,
  :DESC => 9,
  :left_paren => 10,
  :right_paren => 11,
  :INSERT => 12,
  :INTO => 13,
  :VALUES => 14,
  :SELECT => 15,
  :DISTINCTROW => 16,
  :DISTINCT => 17,
  :ALL => 18,
  :asterisk => 19,
  :AS => 20,
  :FROM => 21,
  :CROSS => 22,
  :JOIN => 23,
  :INNER => 24,
  :LEFT => 25,
  :OUTER => 26,
  :RIGHT => 27,
  :FULL => 28,
  :ON => 29,
  :USING => 30,
  :WHERE => 31,
  :GROUP => 32,
  :HAVING => 33,
  :NOT => 34,
  :BETWEEN => 35,
  :AND => 36,
  :IN => 37,
  :LIKE => 38,
  :IS => 39,
  :NULL => 40,
  :EXISTS => 41,
  :identifier => 42,
  :OR => 43,
  :equals_operator => 44,
  :not_equals_operator => 45,
  :less_than_operator => 46,
  :greater_than_operator => 47,
  :less_than_or_equals_operator => 48,
  :greater_than_or_equals_operator => 49,
  :plus_sign => 50,
  :minus_sign => 51,
  :modulo => 52,
  :solidus => 53,
  :CURRENT_USER => 54,
  :period => 55,
  :COUNT => 56,
  :LENGTH => 57,
  :AVG => 58,
  :MAX => 59,
  :MIN => 60,
  :SUM => 61,
  :E => 62,
  :quote => 63,
  :character_string_literal => 64,
  :DATE => 65,
  :date_string => 66,
  :semicolon => 67 }

racc_nt_base = 68

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ORDER",
  "BY",
  "LIMIT",
  "unsigned_integer",
  "OFFSET",
  "comma",
  "ASC",
  "DESC",
  "left_paren",
  "right_paren",
  "INSERT",
  "INTO",
  "VALUES",
  "SELECT",
  "DISTINCTROW",
  "DISTINCT",
  "ALL",
  "asterisk",
  "AS",
  "FROM",
  "CROSS",
  "JOIN",
  "INNER",
  "LEFT",
  "OUTER",
  "RIGHT",
  "FULL",
  "ON",
  "USING",
  "WHERE",
  "GROUP",
  "HAVING",
  "NOT",
  "BETWEEN",
  "AND",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "EXISTS",
  "identifier",
  "OR",
  "equals_operator",
  "not_equals_operator",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "modulo",
  "solidus",
  "CURRENT_USER",
  "period",
  "COUNT",
  "LENGTH",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "E",
  "quote",
  "character_string_literal",
  "DATE",
  "date_string",
  "semicolon",
  "$start",
  "direct_sql_statement",
  "direct_sql_data_statement",
  "direct_select_statement_multiple_rows",
  "insert_specification",
  "query_expression",
  "order_by_clause",
  "sort_specification_list",
  "limit_clause",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "column_reference",
  "set_function_specification",
  "numeric_value_expression",
  "subquery",
  "query_specification",
  "table_reference",
  "value_list",
  "column_list",
  "in_column_list",
  "value_expression",
  "in_value_list",
  "select_list",
  "table_expression",
  "semicolon_not_req",
  "select_sublist",
  "derived_column",
  "column_name",
  "from_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "table_name",
  "joined_table",
  "table_subquery",
  "cross_join",
  "qualified_join",
  "join_type",
  "join_specification",
  "join_condition",
  "named_columns_join",
  "search_condition",
  "join_column_list",
  "column_name_list",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "exact_numeric_literal",
  "row_subquery",
  "between_predicate",
  "row_value_constructor",
  "in_predicate",
  "in_predicate_value",
  "like_predicate",
  "general_literal",
  "null_predicate",
  "exists_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "unsigned_literal",
  "general_value_specification",
  "unsigned_numeric_literal",
  "qualifier",
  "general_set_function",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer",
  "datetime_literal",
  "date_literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.racc', 13)
  def _reduce_4(val, _values, result)
     result = SQLParser::Statement::DirectSelect.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = SQLParser::Statement::OrderBy.new(val[2]) 
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 22)
  def _reduce_8(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_9(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 24)
  def _reduce_10(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[3], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_11(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 12 omitted

module_eval(<<'.,.,', 'parser.racc', 31)
  def _reduce_13(val, _values, result)
     result = val[1].new(val[0]) 
    result
  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_16(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_18(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_19(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 42)
  def _reduce_20(val, _values, result)
     result = SQLParser::Statement::Descending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 47)
  def _reduce_21(val, _values, result)
     result = SQLParser::Statement::Subquery.new(val[1]) 
    result
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'parser.racc', 53)
  def _reduce_23(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], nil, val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 54)
  def _reduce_24(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 57)
  def _reduce_25(val, _values, result)
     result = SQLParser::Statement::InColumnList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_26(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_28(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 67)
  def _reduce_29(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "DISTINCTROW") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_30(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "DISTINCTROW") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 69)
  def _reduce_31(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "DISTINCT") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_32(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "DISTINCT") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_33(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "ALL") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_34(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "ALL") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_35(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_36(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_37(val, _values, result)
     result = SQLParser::Statement::All.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_38(val, _values, result)
     result = SQLParser::Statement::SelectList.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_39(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_41(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_42(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_44(val, _values, result)
     result = SQLParser::Statement::TableExpression.new(val[0], val[1], val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_45(val, _values, result)
     result = SQLParser::Statement::FromClause.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_46(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_47(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.racc', 110)
  def _reduce_54(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 111)
  def _reduce_55(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 114)
  def _reduce_56(val, _values, result)
     result = val[1].new(val[0], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 117)
  def _reduce_57(val, _values, result)
     result = SQLParser::Statement::InnerJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 118)
  def _reduce_58(val, _values, result)
     result = SQLParser::Statement::LeftOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 119)
  def _reduce_59(val, _values, result)
     result = SQLParser::Statement::LeftJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 120)
  def _reduce_60(val, _values, result)
     result = SQLParser::Statement::RightOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 121)
  def _reduce_61(val, _values, result)
     result = SQLParser::Statement::RightJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 122)
  def _reduce_62(val, _values, result)
     result = SQLParser::Statement::FullJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 123)
  def _reduce_63(val, _values, result)
     result = SQLParser::Statement::FullOuterJoin 
    result
  end
.,.,

# reduce 64 omitted

# reduce 65 omitted

module_eval(<<'.,.,', 'parser.racc', 130)
  def _reduce_66(val, _values, result)
     result = SQLParser::Statement::On.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 133)
  def _reduce_67(val, _values, result)
     result = SQLParser::Statement::Using.new(val[2]) 
    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.racc', 140)
  def _reduce_70(val, _values, result)
     result = SQLParser::Statement::WhereClause.new(val[1]) 
    result
  end
.,.,

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.racc', 144)
  def _reduce_72(val, _values, result)
     result = SQLParser::Statement::GroupByClause.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 147)
  def _reduce_73(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.racc', 157)
  def _reduce_79(val, _values, result)
     result = SQLParser::Statement::HavingClause.new(val[1]) 
    result
  end
.,.,

# reduce 80 omitted

module_eval(<<'.,.,', 'parser.racc', 164)
  def _reduce_81(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Between.new(val[0], val[3], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 165)
  def _reduce_82(val, _values, result)
     result = SQLParser::Statement::Between.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 168)
  def _reduce_83(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::In.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 169)
  def _reduce_84(val, _values, result)
     result = SQLParser::Statement::In.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.racc', 173)
  def _reduce_86(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 176)
  def _reduce_87(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 88 omitted

module_eval(<<'.,.,', 'parser.racc', 183)
  def _reduce_89(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Like.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 184)
  def _reduce_90(val, _values, result)
     result = SQLParser::Statement::Like.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 187)
  def _reduce_91(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new)) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 188)
  def _reduce_92(val, _values, result)
     result = SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 191)
  def _reduce_93(val, _values, result)
     result = SQLParser::Statement::Exists.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 195)
  def _reduce_94(val, _values, result)
     result = SQLParser::Statement::Table.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 198)
  def _reduce_95(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 96 omitted

# reduce 97 omitted

module_eval(<<'.,.,', 'parser.racc', 204)
  def _reduce_98(val, _values, result)
     result = SQLParser::Statement::Or.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.racc', 208)
  def _reduce_100(val, _values, result)
     result = SQLParser::Statement::And.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 211)
  def _reduce_101(val, _values, result)
     result = SQLParser::Statement::Not.new(val[1]) 
    result
  end
.,.,

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

module_eval(<<'.,.,', 'parser.racc', 219)
  def _reduce_105(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

module_eval(<<'.,.,', 'parser.racc', 230)
  def _reduce_112(val, _values, result)
     result = SQLParser::Statement::Equals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 231)
  def _reduce_113(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Equals.new(val[0], val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 232)
  def _reduce_114(val, _values, result)
     result = SQLParser::Statement::Less.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 233)
  def _reduce_115(val, _values, result)
     result = SQLParser::Statement::Greater.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 234)
  def _reduce_116(val, _values, result)
     result = SQLParser::Statement::LessOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 235)
  def _reduce_117(val, _values, result)
     result = SQLParser::Statement::GreaterOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

module_eval(<<'.,.,', 'parser.racc', 249)
  def _reduce_123(val, _values, result)
     result = SQLParser::Statement::Add.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 250)
  def _reduce_124(val, _values, result)
     result = SQLParser::Statement::Subtract.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 251)
  def _reduce_125(val, _values, result)
     result = SQLParser::Statement::Modulo.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 126 omitted

module_eval(<<'.,.,', 'parser.racc', 255)
  def _reduce_127(val, _values, result)
     result = SQLParser::Statement::Multiply.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 256)
  def _reduce_128(val, _values, result)
     result = SQLParser::Statement::Divide.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 129 omitted

module_eval(<<'.,.,', 'parser.racc', 260)
  def _reduce_130(val, _values, result)
     result = val[0].new(val[1]) 
    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

module_eval(<<'.,.,', 'parser.racc', 267)
  def _reduce_135(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.racc', 278)
  def _reduce_140(val, _values, result)
     result = SQLParser::Statement::CurrentUser.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_141(val, _values, result)
     result = SQLParser::Statement::QualifiedColumn.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 142 omitted

# reduce 143 omitted

module_eval(<<'.,.,', 'parser.racc', 288)
  def _reduce_144(val, _values, result)
     result = SQLParser::Statement::Count.new(SQLParser::Statement::All.new) 
    result
  end
.,.,

# reduce 145 omitted

module_eval(<<'.,.,', 'parser.racc', 292)
  def _reduce_146(val, _values, result)
     result = SQLParser::Statement::Count.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 293)
  def _reduce_147(val, _values, result)
     result = SQLParser::Statement::Length.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 294)
  def _reduce_148(val, _values, result)
     result = SQLParser::Statement::Average.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 295)
  def _reduce_149(val, _values, result)
     result = SQLParser::Statement::Maximum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 296)
  def _reduce_150(val, _values, result)
     result = SQLParser::Statement::Minimum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 297)
  def _reduce_151(val, _values, result)
     result = SQLParser::Statement::Sum.new(val[2]) 
    result
  end
.,.,

# reduce 152 omitted

# reduce 153 omitted

module_eval(<<'.,.,', 'parser.racc', 305)
  def _reduce_154(val, _values, result)
     result = SQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 306)
  def _reduce_155(val, _values, result)
     result = SQLParser::Statement::Float.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 307)
  def _reduce_156(val, _values, result)
     result = SQLParser::Statement::Float.new("0.#{val[1]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 308)
  def _reduce_157(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 311)
  def _reduce_158(val, _values, result)
     result = SQLParser::Statement::ApproximateFloat.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 159 omitted

# reduce 160 omitted

module_eval(<<'.,.,', 'parser.racc', 320)
  def _reduce_161(val, _values, result)
     result = val[0].new(SQLParser::Statement::Integer.new(val[1])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 321)
  def _reduce_162(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 324)
  def _reduce_163(val, _values, result)
     result = SQLParser::Statement::UnaryPlus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 325)
  def _reduce_164(val, _values, result)
     result = SQLParser::Statement::UnaryMinus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 329)
  def _reduce_165(val, _values, result)
     result = SQLParser::Statement::Column.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 333)
  def _reduce_166(val, _values, result)
     result = SQLParser::Statement::String.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 334)
  def _reduce_167(val, _values, result)
     result = SQLParser::Statement::String.new('') 
    result
  end
.,.,

# reduce 168 omitted

# reduce 169 omitted

module_eval(<<'.,.,', 'parser.racc', 341)
  def _reduce_170(val, _values, result)
     result = SQLParser::Statement::Date.new(val[1]) 
    result
  end
.,.,

# reduce 171 omitted

# reduce 172 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module SQLParser
