#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 348)

def self.parse(sql)
  new.scan_str(sql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    48,   145,  -139,   205,   -16,    31,    59,    80,   117,    74,
    59,   -16,   -16,   -16,   -15,    53,    59,    56,   248,   -14,
    48,   -15,   -15,   -15,   249,    31,   -14,   -14,   -14,   237,
    76,    76,    76,  -139,  -139,  -139,  -139,    21,    66,   274,
    48,    81,    66,   149,   150,    31,    51,    52,    66,    35,
    49,    39,    41,    42,    43,    44,    45,    21,    53,    92,
    56,   205,    48,    96,    95,    51,    52,    31,   276,    35,
    49,    39,    41,    42,    43,    44,    45,    21,    53,   277,
    56,     7,    48,   278,     8,    51,    52,    31,   279,    35,
    49,    39,    41,    42,    43,    44,    45,   280,    53,    21,
    56,   239,    76,   240,   241,   271,   272,    51,    52,     9,
    11,    35,    49,    39,    41,    42,    43,    44,    45,    21,
    53,    48,    56,    53,    12,    56,   165,    51,    52,  -133,
    57,    35,    49,    39,    41,    42,    43,    44,    45,    58,
    53,    48,    56,    77,    78,    79,    31,    72,    73,   -94,
   172,    85,    86,    87,    88,    89,    90,   169,    21,    91,
  -133,  -133,  -133,  -133,  -159,    92,    51,    52,    93,    94,
    35,    49,    39,    41,    42,    43,    44,    45,    21,    53,
    48,    56,    97,     8,    72,   165,    51,    52,    72,    72,
    35,    49,    39,    41,    42,    43,    44,    45,   123,    53,
    48,    56,    76,   110,   132,   242,    76,   141,   146,   172,
   147,   151,   109,   155,    66,   157,   169,    21,   111,   158,
   113,   114,    48,   115,   116,    51,    52,   242,   159,    35,
    49,    39,    41,    42,    43,    44,    45,    21,    53,   160,
    56,   161,    48,    76,   164,    51,    52,   242,   185,    35,
    49,    39,    41,    42,    43,    44,    45,   186,    53,    21,
    56,   187,   188,   189,    48,   190,   191,    51,    52,   242,
   192,    35,    49,    39,    41,    42,    43,    44,    45,    21,
    53,   194,    56,   195,    48,    66,   201,    51,    52,   242,
   202,    35,    49,    39,    41,    42,    43,    44,    45,   205,
    53,    21,    56,    59,   219,   222,    48,   223,   229,    51,
    52,   242,   132,    35,    49,    39,    41,    42,    43,    44,
    45,    21,    53,   244,    56,   259,    48,   260,   205,    51,
    52,   242,   261,    35,    49,    39,    41,    42,    43,    44,
    45,   219,    53,    21,    56,   244,   265,   267,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    21,    53,    48,    56,   nil,   nil,   nil,
   165,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,   nil,    53,    48,    56,   nil,   110,   nil,
    31,   108,   nil,   nil,   172,   109,   nil,   nil,   nil,   nil,
   nil,   169,    21,   111,   nil,   113,   114,   nil,   115,   116,
    51,    52,   nil,   nil,    35,    49,    39,    41,    42,    43,
    44,    45,    21,    53,    48,    56,   nil,   nil,   nil,   165,
    51,    52,   nil,   nil,    35,    49,    39,    41,    42,    43,
    44,    45,   nil,    53,    48,    56,   nil,   nil,   nil,    31,
   nil,   nil,   nil,   172,   nil,   nil,   nil,   nil,    17,   nil,
   169,    21,   nil,   nil,   nil,   nil,   103,   nil,   nil,    51,
    52,    31,   nil,    35,    49,    39,    41,    42,    43,    44,
    45,    21,    53,   nil,    56,   nil,    48,   nil,   nil,    51,
    52,    31,   nil,    35,    49,    39,    41,    42,    43,    44,
    45,   nil,    53,    21,    56,   nil,   nil,   nil,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    21,    53,  -152,    56,   nil,   nil,    48,
   110,    51,    52,   nil,    31,    35,    49,    39,    41,    42,
    43,    44,    45,    17,    53,   111,    56,   113,   114,    48,
   115,   116,   227,   228,   242,   nil,  -152,  -152,  -152,  -152,
   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,  -159,   nil,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    21,    53,   nil,    56,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    48,    53,   nil,    56,
   nil,    31,   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    48,   nil,   nil,   nil,
   nil,    31,   nil,   nil,   206,   207,     8,   208,   209,   210,
   nil,   nil,   nil,    21,   211,   212,   213,   214,   215,   216,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    21,    53,   nil,    56,   nil,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    48,    53,   nil,    56,   nil,    31,   nil,
   nil,   nil,   nil,   nil,    13,    14,    15,    17,   nil,   nil,
   nil,   nil,   nil,    48,   nil,   nil,   nil,   nil,    31,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    21,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,
   nil,   nil,    35,    49,    39,    41,    42,    43,    44,    45,
    21,    53,   nil,    56,   nil,   nil,    48,   nil,    51,    52,
   nil,    31,    35,    49,    39,    41,    42,    43,    44,    45,
    17,    53,   nil,    56,   nil,   nil,    48,   nil,   nil,   nil,
   nil,   242,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,    48,   nil,
   nil,    51,    52,    31,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    21,    53,   nil,    56,   nil,   nil,   nil,
   nil,    51,    52,   nil,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,    48,    53,    21,    56,   nil,   165,   nil,
   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    48,    53,   nil,    56,   nil,
   242,   nil,   172,   nil,   nil,   nil,   nil,   nil,   nil,   169,
    21,   nil,   nil,   nil,   nil,   103,   nil,   nil,    51,    52,
    31,   nil,    35,    49,    39,    41,    42,    43,    44,    45,
   nil,    53,    21,    56,   nil,   nil,   nil,   nil,   nil,   nil,
    51,    52,   nil,   nil,    35,    49,    39,    41,    42,    43,
    44,    45,    21,    53,   nil,    56,   nil,   nil,    48,   nil,
    51,    52,   nil,    31,    35,    49,    39,    41,    42,    43,
    44,    45,   134,    53,   nil,    56,   nil,   nil,    48,   nil,
   nil,   nil,   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,
    48,   nil,   nil,    51,    52,    31,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    21,    53,   nil,    56,   nil,
    48,   nil,   nil,    51,    52,    31,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,   nil,    53,    21,    56,   nil,
   nil,   nil,    48,   nil,   nil,    51,    52,    31,   nil,    35,
    49,    39,    41,    42,    43,    44,    45,    21,    53,   nil,
    56,   nil,    48,   nil,   nil,    51,    52,    31,   nil,    35,
    49,    39,    41,    42,    43,    44,    45,   nil,    53,    21,
    56,   nil,   nil,   nil,   nil,   nil,   nil,    51,    52,   nil,
   nil,    35,    49,    39,    41,    42,    43,    44,    45,    21,
    53,   nil,    56,   nil,   nil,   nil,   nil,    51,    52,   nil,
   nil,    35,    49,    39,    41,    42,    43,    44,    45,    48,
    53,   nil,    56,   nil,   165,   nil,   nil,   nil,   nil,     8,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    48,
   nil,   nil,   nil,   nil,    31,   nil,   nil,   nil,   172,   nil,
   nil,   nil,   nil,   nil,   nil,   169,    21,   nil,   nil,   nil,
   nil,    48,   nil,   nil,    51,    52,    31,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    21,    53,   nil,    56,
   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,
    39,    41,    42,    43,    44,    45,    48,    53,    21,    56,
   nil,   165,   nil,   nil,   nil,   nil,    51,    52,   nil,   nil,
    35,    49,    39,    41,    42,    43,    44,    45,    48,    53,
   nil,    56,   nil,    31,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   169,    21,   nil,   nil,   nil,   nil,    48,   nil,
   nil,    51,    52,    31,   nil,    35,    49,    39,    41,    42,
    43,    44,    45,   nil,    53,    21,    56,   nil,   nil,   nil,
   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,    21,    53,   nil,    56,   nil,
   nil,   nil,   nil,    51,    52,   nil,   nil,    35,    49,    39,
    41,    42,    43,    44,    45,   nil,    53,   nil,    56 ]

racc_action_check = [
    26,    94,    23,   258,   103,    26,    72,    25,    61,    20,
    12,   103,   103,   103,   102,   241,   158,   241,   210,   101,
    78,   102,   102,   102,   210,    78,   101,   101,   101,   203,
    61,    20,   259,    23,    23,    23,    23,    26,    72,   262,
    79,    25,    12,   100,   100,    79,    94,    94,   158,    26,
    26,    26,    26,    26,    26,    26,    26,    78,    26,   103,
    26,   203,    80,    53,    53,    78,    78,    80,   266,    78,
    78,    78,    78,    78,    78,    78,    78,    79,    78,   268,
    78,     0,    81,   269,     0,    79,    79,    81,   271,    79,
    79,    79,    79,    79,    79,    79,    79,   272,    79,    80,
    79,   206,   278,   206,   206,   260,   260,    80,    80,     1,
     5,    80,    80,    80,    80,    80,    80,    80,    80,    81,
    80,   201,    80,   209,     7,   209,   201,    81,    81,   235,
     9,    81,    81,    81,    81,    81,    81,    81,    81,    11,
    81,   202,    81,    24,    24,    24,   202,    16,    19,    21,
   201,    36,    39,    41,    42,    43,    44,   201,   201,    45,
   235,   235,   235,   235,    46,    48,   201,   201,    49,    50,
   201,   201,   201,   201,   201,   201,   201,   201,   202,   201,
   205,   201,    56,    59,    67,   205,   202,   202,    68,    69,
   202,   202,   202,   202,   202,   202,   202,   202,    71,   202,
   207,   202,    74,   124,    84,   207,    85,    92,    95,   205,
    98,   105,   107,   109,   110,   111,   205,   205,   124,   112,
   124,   124,   211,   124,   124,   205,   205,   211,   114,   205,
   205,   205,   205,   205,   205,   205,   205,   207,   205,   115,
   205,   116,   212,   117,   122,   207,   207,   212,   134,   207,
   207,   207,   207,   207,   207,   207,   207,   135,   207,   211,
   207,   136,   137,   138,   213,   139,   140,   211,   211,   213,
   144,   211,   211,   211,   211,   211,   211,   211,   211,   212,
   211,   153,   211,   154,   214,   157,   163,   212,   212,   214,
   164,   212,   212,   212,   212,   212,   212,   212,   212,   166,
   212,   213,   212,   169,   170,   196,   215,   197,   200,   213,
   213,   215,   204,   213,   213,   213,   213,   213,   213,   213,
   213,   214,   213,   208,   213,   228,   216,   229,   231,   214,
   214,   216,   232,   214,   214,   214,   214,   214,   214,   214,
   214,   238,   214,   215,   214,   240,   243,   248,   nil,   nil,
   nil,   215,   215,   nil,   nil,   215,   215,   215,   215,   215,
   215,   215,   215,   216,   215,   219,   215,   nil,   nil,   nil,
   219,   216,   216,   nil,   nil,   216,   216,   216,   216,   216,
   216,   216,   216,   nil,   216,   223,   216,   nil,    60,   nil,
   223,    60,   nil,   nil,   219,    60,   nil,   nil,   nil,   nil,
   nil,   219,   219,    60,   nil,    60,    60,   nil,    60,    60,
   219,   219,   nil,   nil,   219,   219,   219,   219,   219,   219,
   219,   219,   223,   219,   227,   219,   nil,   nil,   nil,   227,
   223,   223,   nil,   nil,   223,   223,   223,   223,   223,   223,
   223,   223,   nil,   223,    14,   223,   nil,   nil,   nil,    14,
   nil,   nil,   nil,   227,   nil,   nil,   nil,   nil,    14,   nil,
   227,   227,   nil,   nil,   nil,   nil,    58,   nil,   nil,   227,
   227,    58,   nil,   227,   227,   227,   227,   227,   227,   227,
   227,    14,   227,   nil,   227,   nil,   108,   nil,   nil,    14,
    14,   108,   nil,    14,    14,    14,    14,    14,    14,    14,
    14,   nil,    14,    58,    14,   nil,   nil,   nil,   nil,   nil,
   nil,    58,    58,   nil,   nil,    58,    58,    58,    58,    58,
    58,    58,    58,   108,    58,   234,    58,   nil,   nil,    15,
   199,   108,   108,   nil,    15,   108,   108,   108,   108,   108,
   108,   108,   108,    15,   108,   199,   108,   199,   199,   239,
   199,   199,   199,   199,   239,   nil,   234,   234,   234,   234,
   nil,   nil,   nil,   nil,   nil,   nil,    15,   nil,   234,   nil,
   nil,   nil,   nil,   nil,    15,    15,   nil,   nil,    15,    15,
    15,    15,    15,    15,    15,    15,   239,    15,   nil,    15,
   nil,   nil,   nil,   nil,   239,   239,   nil,   nil,   239,   239,
   239,   239,   239,   239,   239,   239,   242,   239,   nil,   239,
   nil,   242,   nil,   nil,   nil,   nil,   242,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   244,   nil,   nil,   nil,
   nil,   244,   nil,   nil,   168,   168,   244,   168,   168,   168,
   nil,   nil,   nil,   242,   168,   168,   168,   168,   168,   168,
   nil,   242,   242,   nil,   nil,   242,   242,   242,   242,   242,
   242,   242,   242,   244,   242,   nil,   242,   nil,   nil,   nil,
   nil,   244,   244,   nil,   nil,   244,   244,   244,   244,   244,
   244,   244,   244,     8,   244,   nil,   244,   nil,     8,   nil,
   nil,   nil,   nil,   nil,     8,     8,     8,     8,   nil,   nil,
   nil,   nil,   nil,   261,   nil,   nil,   nil,   nil,   261,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     8,     8,
   nil,   nil,     8,     8,     8,     8,     8,     8,     8,     8,
   261,     8,   nil,     8,   nil,   nil,    13,   nil,   261,   261,
   nil,    13,   261,   261,   261,   261,   261,   261,   261,   261,
    13,   261,   nil,   261,   nil,   nil,   265,   nil,   nil,   nil,
   nil,   265,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,    73,   nil,
   nil,    13,    13,    73,   nil,    13,    13,    13,    13,    13,
    13,    13,    13,   265,    13,   nil,    13,   nil,   nil,   nil,
   nil,   265,   265,   nil,   nil,   265,   265,   265,   265,   265,
   265,   265,   265,   123,   265,    73,   265,   nil,   123,   nil,
   nil,   nil,   nil,    73,    73,   nil,   nil,    73,    73,    73,
    73,    73,    73,    73,    73,   274,    73,   nil,    73,   nil,
   274,   nil,   123,   nil,   nil,   nil,   nil,   nil,   nil,   123,
   123,   nil,   nil,   nil,   nil,   147,   nil,   nil,   123,   123,
   147,   nil,   123,   123,   123,   123,   123,   123,   123,   123,
   nil,   123,   274,   123,   nil,   nil,   nil,   nil,   nil,   nil,
   274,   274,   nil,   nil,   274,   274,   274,   274,   274,   274,
   274,   274,   147,   274,   nil,   274,   nil,   nil,    86,   nil,
   147,   147,   nil,    86,   147,   147,   147,   147,   147,   147,
   147,   147,    86,   147,   nil,   147,   nil,   nil,    87,   nil,
   nil,   nil,   nil,    87,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    86,   nil,   nil,   nil,   nil,
   155,   nil,   nil,    86,    86,   155,   nil,    86,    86,    86,
    86,    86,    86,    86,    86,    87,    86,   nil,    86,   nil,
    88,   nil,   nil,    87,    87,    88,   nil,    87,    87,    87,
    87,    87,    87,    87,    87,   nil,    87,   155,    87,   nil,
   nil,   nil,    89,   nil,   nil,   155,   155,    89,   nil,   155,
   155,   155,   155,   155,   155,   155,   155,    88,   155,   nil,
   155,   nil,    90,   nil,   nil,    88,    88,    90,   nil,    88,
    88,    88,    88,    88,    88,    88,    88,   nil,    88,    89,
    88,   nil,   nil,   nil,   nil,   nil,   nil,    89,    89,   nil,
   nil,    89,    89,    89,    89,    89,    89,    89,    89,    90,
    89,   nil,    89,   nil,   nil,   nil,   nil,    90,    90,   nil,
   nil,    90,    90,    90,    90,    90,    90,    90,    90,   165,
    90,   nil,    90,   nil,   165,   nil,   nil,   nil,   nil,   165,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    91,
   nil,   nil,   nil,   nil,    91,   nil,   nil,   nil,   165,   nil,
   nil,   nil,   nil,   nil,   nil,   165,   165,   nil,   nil,   nil,
   nil,    77,   nil,   nil,   165,   165,    77,   nil,   165,   165,
   165,   165,   165,   165,   165,   165,    91,   165,   nil,   165,
   nil,   nil,   nil,   nil,    91,    91,   nil,   nil,    91,    91,
    91,    91,    91,    91,    91,    91,   172,    91,    77,    91,
   nil,   172,   nil,   nil,   nil,   nil,    77,    77,   nil,   nil,
    77,    77,    77,    77,    77,    77,    77,    77,   195,    77,
   nil,    77,   nil,   195,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   172,   172,   nil,   nil,   nil,   nil,    31,   nil,
   nil,   172,   172,    31,   nil,   172,   172,   172,   172,   172,
   172,   172,   172,   nil,   172,   195,   172,   nil,   nil,   nil,
   nil,   nil,   nil,   195,   195,   nil,   nil,   195,   195,   195,
   195,   195,   195,   195,   195,    31,   195,   nil,   195,   nil,
   nil,   nil,   nil,    31,    31,   nil,   nil,    31,    31,    31,
    31,    31,    31,    31,    31,   nil,    31,   nil,    31 ]

racc_action_pointer = [
    69,   109,   nil,   nil,   nil,   108,   nil,   111,   678,   130,
   nil,   136,     0,   741,   439,   524,   126,   nil,   nil,   141,
   -11,    94,   nil,   -17,    93,   -12,    -5,   nil,   nil,   nil,
   nil,  1183,   nil,   nil,   nil,   nil,    96,   nil,   nil,   142,
   nil,   143,   144,   145,   146,   149,   102,   nil,   110,   163,
   107,   nil,   nil,     0,   nil,   nil,   116,   nil,   461,   168,
   381,   -12,   nil,   nil,   nil,   nil,   nil,   163,   167,   168,
   nil,   167,    -4,   783,   160,   nil,   nil,  1106,    15,    35,
    57,    77,   nil,   nil,   193,   164,   903,   923,   965,   987,
  1007,  1084,   202,   nil,    -4,   145,   nil,   nil,   203,   nil,
    35,    19,    14,     4,   nil,   200,   nil,   198,   481,   203,
   172,   192,   196,   nil,   202,   213,   215,   201,   nil,   nil,
   nil,   nil,   212,   818,   196,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   237,   246,   250,   251,   252,   254,
   255,   nil,   nil,   nil,   265,   nil,   nil,   860,   nil,   nil,
   nil,   nil,   nil,   270,   276,   945,   nil,   243,     6,   nil,
   nil,   nil,   nil,   253,   287,  1064,   256,   nil,   600,   293,
   268,   nil,  1141,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,  1163,   294,   300,   nil,   523,
   304,   116,   136,    18,   301,   175,    66,   195,   313,    60,
   -16,   217,   237,   259,   279,   301,   321,   nil,   nil,   360,
   nil,   nil,   nil,   380,   nil,   nil,   nil,   419,   315,   322,
   nil,   285,   325,   nil,   506,   110,   nil,   nil,   305,   544,
   335,   -48,   601,   310,   621,   nil,   nil,   nil,   307,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -40,   -10,
    99,   698,     3,   nil,   nil,   761,    57,   nil,    68,    76,
   nil,    83,    92,   nil,   840,   nil,   nil,   nil,    60,   nil,
   nil,   nil,   nil ]

racc_action_default = [
  -171,  -171,    -1,    -2,    -3,    -5,   -22,  -171,  -171,  -171,
    -4,  -171,  -171,  -171,  -171,  -171,   -36,   -37,   -38,   -40,
   -43,  -165,  -121,  -122,  -126,  -129,  -171,  -131,  -132,  -133,
  -134,  -171,  -136,  -137,  -138,  -140,  -171,  -142,  -143,  -171,
  -145,  -171,  -171,  -171,  -171,  -171,  -152,  -153,  -157,  -171,
  -171,  -163,  -164,  -171,  -168,  -169,  -171,   283,  -171,  -171,
  -171,   -48,   -49,   -50,   -52,   -53,   -94,   -30,   -32,   -34,
   -35,   -69,  -171,  -171,  -171,   -42,  -165,  -171,  -171,  -171,
  -171,  -171,  -130,  -139,  -171,  -171,  -171,  -171,  -171,  -171,
  -171,  -171,  -155,  -156,  -171,  -171,  -167,  -170,    -6,   -12,
   -18,  -133,  -134,  -157,   -17,  -171,   -23,  -171,  -171,  -171,
  -171,  -171,  -171,   -57,   -59,   -61,   -62,  -171,   -47,   -29,
   -31,   -33,   -71,  -171,   -45,   -39,   -41,  -123,  -124,  -125,
  -127,  -128,  -135,  -141,  -171,  -171,  -171,  -171,  -171,  -171,
  -171,  -154,  -158,  -160,  -171,  -162,  -166,  -171,   -13,   -19,
   -20,   -21,   -24,  -171,   -27,  -171,   -54,  -171,  -171,   -58,
   -60,   -63,   -46,   -78,  -171,  -171,   -70,   -80,  -171,  -171,
   -97,   -99,  -171,  -102,  -103,  -104,  -106,  -107,  -108,  -109,
  -110,  -111,  -118,  -119,  -120,  -144,  -146,  -147,  -148,  -149,
  -150,  -151,  -161,   -11,   -25,  -171,  -171,   -88,   -55,  -171,
    -7,  -171,  -171,  -171,  -120,  -171,  -171,  -171,  -171,  -171,
  -171,  -171,  -171,  -171,  -171,  -171,  -171,   -51,   -93,  -171,
  -101,   -26,   -28,  -171,   -56,   -64,   -65,  -171,  -171,  -171,
   -44,   -79,   -72,   -74,   -75,   -76,   -77,  -105,   -98,  -171,
  -171,  -171,  -171,  -171,  -171,   -84,   -85,   -90,  -171,   -92,
  -112,  -113,  -114,  -115,  -116,  -117,  -100,   -87,   -66,  -171,
    -8,  -171,  -171,   -83,   -89,  -171,  -171,   -91,  -171,   -68,
   -96,  -171,  -171,   -73,  -171,   -82,   -86,   -67,  -171,    -9,
   -10,   -81,   -95 ]

racc_goto_table = [
    75,    20,   104,   101,    62,    99,    20,    20,    20,   166,
   196,   102,   106,    60,   245,   153,    83,    61,   130,   131,
   238,   127,   128,   129,    84,   256,   233,   220,   243,   234,
   144,    82,   250,   251,   252,   253,   254,   255,    16,   142,
     1,   118,   143,    67,    68,    69,   263,     2,    83,     3,
     4,   203,    70,     5,   126,    10,    98,   230,   148,   152,
   262,   107,   125,   122,    62,   133,    20,    83,    83,    83,
    83,    83,   163,   124,   200,   218,   224,    61,   257,   135,
   136,   137,   138,   139,   140,   273,   275,   231,   234,   225,
   226,   104,   101,   268,   193,   281,   269,   162,   232,   266,
   102,   154,   221,   119,   120,   121,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   258,   nil,   156,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    83,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   236,   235,   197,   nil,
    62,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   204,   199,
   nil,   217,   198,    61,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   154,   nil,
   nil,   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   247,
   217,   nil,   nil,   nil,   nil,   236,   235,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   197,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   264,   217,   nil,   nil,    84,   nil,   197,   nil,   270,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    83,   nil,   nil,   nil,   nil,   nil,   nil,   282 ]

racc_goto_check = [
    27,    21,    14,    12,    15,     9,    21,    21,    21,    41,
    22,    13,    18,    17,    51,    20,    53,    32,    63,    63,
    56,    14,    14,    14,    21,    57,    45,    58,    49,    46,
    65,    66,    49,    49,    49,    49,    49,    49,    23,    75,
     1,    27,    76,    23,    23,    23,    51,     2,    53,     3,
     4,    41,    24,     5,    27,     6,     7,     8,    11,    18,
    49,    19,    25,    29,    15,    27,    21,    53,    53,    53,
    53,    53,    30,    17,    31,    34,    38,    32,    22,    21,
    21,    21,    21,    21,    21,    45,    49,    41,    46,    39,
    40,    14,    12,    42,     9,    49,    43,    27,    44,    22,
    13,    21,    20,    24,    24,    24,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    41,   nil,    32,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    53,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    14,    12,    21,   nil,
    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,    17,
   nil,    15,    32,    32,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,
   nil,   nil,    53,   nil,   nil,   nil,   nil,   nil,   nil,    53,
    15,   nil,   nil,   nil,   nil,    14,    12,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    53,    15,   nil,   nil,    21,   nil,    21,   nil,    27,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    53,   nil,   nil,   nil,   nil,   nil,   nil,    27 ]

racc_goto_pointer = [
   nil,    40,    47,    49,    50,    53,    50,    -2,  -143,   -53,
   nil,   -42,   -55,   -47,   -56,    -8,   nil,     1,   -48,     1,
   -93,    -7,  -145,    30,    36,   -11,   nil,   -20,   nil,    -8,
   -50,   -89,     5,   nil,   -94,   nil,   nil,   nil,  -123,  -110,
  -109,  -114,  -166,  -163,  -104,  -176,  -173,   nil,   nil,  -179,
   nil,  -194,   nil,   -10,   nil,   nil,  -185,  -194,  -145,   nil,
   nil,   nil,   nil,   -62,   nil,   -64,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   -55,   -52,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   105,   nil,   nil,   nil,   nil,
   100,   nil,    29,    30,    22,   167,     6,   nil,   nil,   nil,
   nil,   184,   nil,   nil,   nil,    18,    19,    37,    71,   nil,
   nil,   nil,    38,    63,   246,    64,    65,   112,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    46,   183,   177,   168,
   178,   nil,   179,    23,   180,   181,   170,   171,   173,   174,
   175,   176,   182,    24,    25,    26,    27,    28,    32,    33,
    34,    36,    40,    47,    50,   nil,   nil,    54,    55 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 68, :_reduce_none,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  2, 70, :_reduce_4,
  0, 73, :_reduce_none,
  3, 73, :_reduce_6,
  0, 75, :_reduce_none,
  2, 75, :_reduce_8,
  4, 75, :_reduce_9,
  4, 75, :_reduce_10,
  3, 74, :_reduce_11,
  1, 74, :_reduce_none,
  2, 76, :_reduce_13,
  1, 77, :_reduce_none,
  1, 77, :_reduce_none,
  1, 77, :_reduce_16,
  1, 77, :_reduce_none,
  0, 78, :_reduce_18,
  1, 78, :_reduce_19,
  1, 78, :_reduce_20,
  3, 82, :_reduce_21,
  1, 72, :_reduce_none,
  4, 71, :_reduce_23,
  5, 71, :_reduce_24,
  3, 86, :_reduce_25,
  3, 87, :_reduce_26,
  1, 87, :_reduce_none,
  4, 85, :_reduce_28,
  4, 83, :_reduce_29,
  3, 83, :_reduce_30,
  4, 83, :_reduce_31,
  3, 83, :_reduce_32,
  4, 83, :_reduce_33,
  3, 83, :_reduce_34,
  3, 83, :_reduce_35,
  2, 83, :_reduce_36,
  1, 90, :_reduce_37,
  1, 90, :_reduce_38,
  3, 92, :_reduce_39,
  1, 92, :_reduce_none,
  3, 93, :_reduce_41,
  2, 93, :_reduce_42,
  1, 93, :_reduce_none,
  5, 91, :_reduce_44,
  2, 95, :_reduce_45,
  3, 84, :_reduce_46,
  2, 84, :_reduce_47,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 101, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  3, 102, :_reduce_54,
  4, 102, :_reduce_55,
  5, 103, :_reduce_56,
  1, 104, :_reduce_57,
  2, 104, :_reduce_58,
  1, 104, :_reduce_59,
  2, 104, :_reduce_60,
  1, 104, :_reduce_61,
  1, 104, :_reduce_62,
  2, 104, :_reduce_63,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  2, 106, :_reduce_66,
  4, 107, :_reduce_67,
  1, 109, :_reduce_none,
  0, 96, :_reduce_none,
  2, 96, :_reduce_70,
  0, 97, :_reduce_none,
  3, 97, :_reduce_72,
  3, 111, :_reduce_73,
  1, 111, :_reduce_none,
  1, 112, :_reduce_none,
  1, 112, :_reduce_none,
  1, 112, :_reduce_none,
  0, 98, :_reduce_none,
  2, 98, :_reduce_79,
  1, 114, :_reduce_none,
  6, 115, :_reduce_81,
  5, 115, :_reduce_82,
  4, 117, :_reduce_83,
  3, 117, :_reduce_84,
  1, 118, :_reduce_none,
  3, 118, :_reduce_86,
  3, 89, :_reduce_87,
  1, 89, :_reduce_none,
  4, 119, :_reduce_89,
  3, 119, :_reduce_90,
  4, 121, :_reduce_91,
  3, 121, :_reduce_92,
  2, 122, :_reduce_93,
  1, 99, :_reduce_94,
  3, 110, :_reduce_95,
  1, 110, :_reduce_none,
  1, 108, :_reduce_none,
  3, 108, :_reduce_98,
  1, 123, :_reduce_none,
  3, 123, :_reduce_100,
  2, 124, :_reduce_101,
  1, 124, :_reduce_none,
  1, 125, :_reduce_none,
  1, 126, :_reduce_none,
  3, 126, :_reduce_105,
  1, 127, :_reduce_none,
  1, 127, :_reduce_none,
  1, 127, :_reduce_none,
  1, 127, :_reduce_none,
  1, 127, :_reduce_none,
  1, 127, :_reduce_none,
  3, 128, :_reduce_112,
  3, 128, :_reduce_113,
  3, 128, :_reduce_114,
  3, 128, :_reduce_115,
  3, 128, :_reduce_116,
  3, 128, :_reduce_117,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  1, 129, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  3, 81, :_reduce_123,
  3, 81, :_reduce_124,
  3, 81, :_reduce_125,
  1, 81, :_reduce_none,
  3, 130, :_reduce_127,
  3, 130, :_reduce_128,
  1, 130, :_reduce_none,
  2, 131, :_reduce_130,
  1, 131, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  1, 133, :_reduce_none,
  3, 133, :_reduce_135,
  1, 134, :_reduce_none,
  1, 134, :_reduce_none,
  1, 135, :_reduce_none,
  1, 135, :_reduce_none,
  1, 136, :_reduce_140,
  3, 79, :_reduce_141,
  1, 79, :_reduce_none,
  1, 138, :_reduce_none,
  4, 80, :_reduce_144,
  1, 80, :_reduce_none,
  4, 139, :_reduce_146,
  4, 139, :_reduce_147,
  4, 139, :_reduce_148,
  4, 139, :_reduce_149,
  4, 139, :_reduce_150,
  4, 139, :_reduce_151,
  1, 137, :_reduce_none,
  1, 137, :_reduce_none,
  3, 113, :_reduce_154,
  2, 113, :_reduce_155,
  2, 113, :_reduce_156,
  1, 113, :_reduce_157,
  3, 140, :_reduce_158,
  1, 141, :_reduce_none,
  1, 142, :_reduce_none,
  2, 143, :_reduce_161,
  1, 143, :_reduce_162,
  1, 132, :_reduce_163,
  1, 132, :_reduce_164,
  1, 94, :_reduce_165,
  3, 120, :_reduce_166,
  2, 120, :_reduce_167,
  1, 120, :_reduce_none,
  1, 144, :_reduce_none,
  2, 145, :_reduce_170 ]

racc_reduce_n = 171

racc_shift_n = 283

racc_token_table = {
  false => 0,
  :error => 1,
  :ORDER => 2,
  :BY => 3,
  :LIMIT => 4,
  :unsigned_integer => 5,
  :OFFSET => 6,
  :comma => 7,
  :ASC => 8,
  :DESC => 9,
  :left_paren => 10,
  :right_paren => 11,
  :INSERT => 12,
  :INTO => 13,
  :VALUES => 14,
  :SELECT => 15,
  :DISTINCTROW => 16,
  :DISTINCT => 17,
  :ALL => 18,
  :asterisk => 19,
  :AS => 20,
  :FROM => 21,
  :CROSS => 22,
  :JOIN => 23,
  :INNER => 24,
  :LEFT => 25,
  :OUTER => 26,
  :RIGHT => 27,
  :FULL => 28,
  :ON => 29,
  :USING => 30,
  :WHERE => 31,
  :GROUP => 32,
  :HAVING => 33,
  :NOT => 34,
  :BETWEEN => 35,
  :AND => 36,
  :IN => 37,
  :LIKE => 38,
  :IS => 39,
  :NULL => 40,
  :EXISTS => 41,
  :identifier => 42,
  :OR => 43,
  :equals_operator => 44,
  :not_equals_operator => 45,
  :less_than_operator => 46,
  :greater_than_operator => 47,
  :less_than_or_equals_operator => 48,
  :greater_than_or_equals_operator => 49,
  :plus_sign => 50,
  :minus_sign => 51,
  :modulo => 52,
  :solidus => 53,
  :CURRENT_USER => 54,
  :period => 55,
  :COUNT => 56,
  :LENGTH => 57,
  :AVG => 58,
  :MAX => 59,
  :MIN => 60,
  :SUM => 61,
  :E => 62,
  :quote => 63,
  :character_string_literal => 64,
  :DATE => 65,
  :date_string => 66 }

racc_nt_base = 67

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ORDER",
  "BY",
  "LIMIT",
  "unsigned_integer",
  "OFFSET",
  "comma",
  "ASC",
  "DESC",
  "left_paren",
  "right_paren",
  "INSERT",
  "INTO",
  "VALUES",
  "SELECT",
  "DISTINCTROW",
  "DISTINCT",
  "ALL",
  "asterisk",
  "AS",
  "FROM",
  "CROSS",
  "JOIN",
  "INNER",
  "LEFT",
  "OUTER",
  "RIGHT",
  "FULL",
  "ON",
  "USING",
  "WHERE",
  "GROUP",
  "HAVING",
  "NOT",
  "BETWEEN",
  "AND",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "EXISTS",
  "identifier",
  "OR",
  "equals_operator",
  "not_equals_operator",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "modulo",
  "solidus",
  "CURRENT_USER",
  "period",
  "COUNT",
  "LENGTH",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "E",
  "quote",
  "character_string_literal",
  "DATE",
  "date_string",
  "$start",
  "direct_sql_statement",
  "direct_sql_data_statement",
  "direct_select_statement_multiple_rows",
  "insert_specification",
  "query_expression",
  "order_by_clause",
  "sort_specification_list",
  "limit_clause",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "column_reference",
  "set_function_specification",
  "numeric_value_expression",
  "subquery",
  "query_specification",
  "table_reference",
  "value_list",
  "column_list",
  "in_column_list",
  "value_expression",
  "in_value_list",
  "select_list",
  "table_expression",
  "select_sublist",
  "derived_column",
  "column_name",
  "from_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "table_name",
  "joined_table",
  "table_subquery",
  "cross_join",
  "qualified_join",
  "join_type",
  "join_specification",
  "join_condition",
  "named_columns_join",
  "search_condition",
  "join_column_list",
  "column_name_list",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "exact_numeric_literal",
  "row_subquery",
  "between_predicate",
  "row_value_constructor",
  "in_predicate",
  "in_predicate_value",
  "like_predicate",
  "general_literal",
  "null_predicate",
  "exists_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "unsigned_literal",
  "general_value_specification",
  "unsigned_numeric_literal",
  "qualifier",
  "general_set_function",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer",
  "datetime_literal",
  "date_literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.racc', 13)
  def _reduce_4(val, _values, result)
     result = SQLParser::Statement::DirectSelect.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = SQLParser::Statement::OrderBy.new(val[2]) 
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 22)
  def _reduce_8(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_9(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 24)
  def _reduce_10(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(val[3], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_11(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 12 omitted

module_eval(<<'.,.,', 'parser.racc', 31)
  def _reduce_13(val, _values, result)
     result = val[1].new(val[0]) 
    result
  end
.,.,

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_16(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_18(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_19(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 42)
  def _reduce_20(val, _values, result)
     result = SQLParser::Statement::Descending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 47)
  def _reduce_21(val, _values, result)
     result = SQLParser::Statement::Subquery.new(val[1]) 
    result
  end
.,.,

# reduce 22 omitted

module_eval(<<'.,.,', 'parser.racc', 53)
  def _reduce_23(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], nil, val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 54)
  def _reduce_24(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 57)
  def _reduce_25(val, _values, result)
     result = SQLParser::Statement::InColumnList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_26(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_28(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 67)
  def _reduce_29(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "DISTINCTROW") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_30(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "DISTINCTROW") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 69)
  def _reduce_31(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "DISTINCT") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_32(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "DISTINCT") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_33(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], val[3], "ALL") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_34(val, _values, result)
     result = SQLParser::Statement::Select.new(val[2], nil, "ALL") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_35(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_36(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_37(val, _values, result)
     result = SQLParser::Statement::All.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_38(val, _values, result)
     result = SQLParser::Statement::SelectList.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_39(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_41(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_42(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_44(val, _values, result)
     result = SQLParser::Statement::TableExpression.new(val[0], val[1], val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_45(val, _values, result)
     result = SQLParser::Statement::FromClause.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_46(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_47(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.racc', 110)
  def _reduce_54(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 111)
  def _reduce_55(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 114)
  def _reduce_56(val, _values, result)
     result = val[1].new(val[0], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 117)
  def _reduce_57(val, _values, result)
     result = SQLParser::Statement::InnerJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 118)
  def _reduce_58(val, _values, result)
     result = SQLParser::Statement::LeftOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 119)
  def _reduce_59(val, _values, result)
     result = SQLParser::Statement::LeftJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 120)
  def _reduce_60(val, _values, result)
     result = SQLParser::Statement::RightOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 121)
  def _reduce_61(val, _values, result)
     result = SQLParser::Statement::RightJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 122)
  def _reduce_62(val, _values, result)
     result = SQLParser::Statement::FullJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 123)
  def _reduce_63(val, _values, result)
     result = SQLParser::Statement::FullOuterJoin 
    result
  end
.,.,

# reduce 64 omitted

# reduce 65 omitted

module_eval(<<'.,.,', 'parser.racc', 130)
  def _reduce_66(val, _values, result)
     result = SQLParser::Statement::On.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 133)
  def _reduce_67(val, _values, result)
     result = SQLParser::Statement::Using.new(val[2]) 
    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.racc', 140)
  def _reduce_70(val, _values, result)
     result = SQLParser::Statement::WhereClause.new(val[1]) 
    result
  end
.,.,

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.racc', 144)
  def _reduce_72(val, _values, result)
     result = SQLParser::Statement::GroupByClause.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 147)
  def _reduce_73(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.racc', 157)
  def _reduce_79(val, _values, result)
     result = SQLParser::Statement::HavingClause.new(val[1]) 
    result
  end
.,.,

# reduce 80 omitted

module_eval(<<'.,.,', 'parser.racc', 164)
  def _reduce_81(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Between.new(val[0], val[3], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 165)
  def _reduce_82(val, _values, result)
     result = SQLParser::Statement::Between.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 168)
  def _reduce_83(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::In.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 169)
  def _reduce_84(val, _values, result)
     result = SQLParser::Statement::In.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.racc', 173)
  def _reduce_86(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 176)
  def _reduce_87(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 88 omitted

module_eval(<<'.,.,', 'parser.racc', 183)
  def _reduce_89(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Like.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 184)
  def _reduce_90(val, _values, result)
     result = SQLParser::Statement::Like.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 187)
  def _reduce_91(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new)) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 188)
  def _reduce_92(val, _values, result)
     result = SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 191)
  def _reduce_93(val, _values, result)
     result = SQLParser::Statement::Exists.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 195)
  def _reduce_94(val, _values, result)
     result = SQLParser::Statement::Table.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 198)
  def _reduce_95(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 96 omitted

# reduce 97 omitted

module_eval(<<'.,.,', 'parser.racc', 204)
  def _reduce_98(val, _values, result)
     result = SQLParser::Statement::Or.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.racc', 208)
  def _reduce_100(val, _values, result)
     result = SQLParser::Statement::And.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 211)
  def _reduce_101(val, _values, result)
     result = SQLParser::Statement::Not.new(val[1]) 
    result
  end
.,.,

# reduce 102 omitted

# reduce 103 omitted

# reduce 104 omitted

module_eval(<<'.,.,', 'parser.racc', 219)
  def _reduce_105(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

module_eval(<<'.,.,', 'parser.racc', 230)
  def _reduce_112(val, _values, result)
     result = SQLParser::Statement::Equals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 231)
  def _reduce_113(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Equals.new(val[0], val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 232)
  def _reduce_114(val, _values, result)
     result = SQLParser::Statement::Less.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 233)
  def _reduce_115(val, _values, result)
     result = SQLParser::Statement::Greater.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 234)
  def _reduce_116(val, _values, result)
     result = SQLParser::Statement::LessOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 235)
  def _reduce_117(val, _values, result)
     result = SQLParser::Statement::GreaterOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

module_eval(<<'.,.,', 'parser.racc', 249)
  def _reduce_123(val, _values, result)
     result = SQLParser::Statement::Add.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 250)
  def _reduce_124(val, _values, result)
     result = SQLParser::Statement::Subtract.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 251)
  def _reduce_125(val, _values, result)
     result = SQLParser::Statement::Modulo.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 126 omitted

module_eval(<<'.,.,', 'parser.racc', 255)
  def _reduce_127(val, _values, result)
     result = SQLParser::Statement::Multiply.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 256)
  def _reduce_128(val, _values, result)
     result = SQLParser::Statement::Divide.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 129 omitted

module_eval(<<'.,.,', 'parser.racc', 260)
  def _reduce_130(val, _values, result)
     result = val[0].new(val[1]) 
    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

module_eval(<<'.,.,', 'parser.racc', 267)
  def _reduce_135(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.racc', 278)
  def _reduce_140(val, _values, result)
     result = SQLParser::Statement::CurrentUser.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_141(val, _values, result)
     result = SQLParser::Statement::QualifiedColumn.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 142 omitted

# reduce 143 omitted

module_eval(<<'.,.,', 'parser.racc', 288)
  def _reduce_144(val, _values, result)
     result = SQLParser::Statement::Count.new(SQLParser::Statement::All.new) 
    result
  end
.,.,

# reduce 145 omitted

module_eval(<<'.,.,', 'parser.racc', 292)
  def _reduce_146(val, _values, result)
     result = SQLParser::Statement::Count.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 293)
  def _reduce_147(val, _values, result)
     result = SQLParser::Statement::Length.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 294)
  def _reduce_148(val, _values, result)
     result = SQLParser::Statement::Average.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 295)
  def _reduce_149(val, _values, result)
     result = SQLParser::Statement::Maximum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 296)
  def _reduce_150(val, _values, result)
     result = SQLParser::Statement::Minimum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 297)
  def _reduce_151(val, _values, result)
     result = SQLParser::Statement::Sum.new(val[2]) 
    result
  end
.,.,

# reduce 152 omitted

# reduce 153 omitted

module_eval(<<'.,.,', 'parser.racc', 305)
  def _reduce_154(val, _values, result)
     result = SQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 306)
  def _reduce_155(val, _values, result)
     result = SQLParser::Statement::Float.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 307)
  def _reduce_156(val, _values, result)
     result = SQLParser::Statement::Float.new("0.#{val[1]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 308)
  def _reduce_157(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 311)
  def _reduce_158(val, _values, result)
     result = SQLParser::Statement::ApproximateFloat.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 159 omitted

# reduce 160 omitted

module_eval(<<'.,.,', 'parser.racc', 320)
  def _reduce_161(val, _values, result)
     result = val[0].new(SQLParser::Statement::Integer.new(val[1])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 321)
  def _reduce_162(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 324)
  def _reduce_163(val, _values, result)
     result = SQLParser::Statement::UnaryPlus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 325)
  def _reduce_164(val, _values, result)
     result = SQLParser::Statement::UnaryMinus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 329)
  def _reduce_165(val, _values, result)
     result = SQLParser::Statement::Column.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 333)
  def _reduce_166(val, _values, result)
     result = SQLParser::Statement::String.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 334)
  def _reduce_167(val, _values, result)
     result = SQLParser::Statement::String.new('') 
    result
  end
.,.,

# reduce 168 omitted

# reduce 169 omitted

module_eval(<<'.,.,', 'parser.racc', 341)
  def _reduce_170(val, _values, result)
     result = SQLParser::Statement::Date.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module SQLParser
